# This rule is not used by the project moodle-lms-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to moodle.bsu.by resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: moodle-lms-operator
    app.kubernetes.io/managed-by: kustomize
  name: moodletenant-viewer-role
rules:
- apiGroups:
  - moodle.bsu.by
  resources:
  - moodletenants
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - moodle.bsu.by
  resources:
  - moodletenants/status
  verbs:
  - get
